services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    hostname: qbittorrent.internal
    dns:
      - 1.1.1.1
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Berlin
      - WEBUI_PORTS=8080/tcp,8080/udp
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=proton
      - VPN_LAN_NETWORK=192.168.0.0/24
      - VPN_LAN_LEAK_ENABLED=false
      - VPN_EXPOSE_PORTS_ON_LAN=8118/tcp,8118/udp
      - VPN_AUTO_PORT_FORWARD=true
      - VPN_KEEP_LOCAL_DNS=false
      - VPN_FIREWALL_TYPE=auto
      - VPN_HEALTHCHECK_ENABLED=false
      - PRIVOXY_ENABLED=false
      - UNBOUND_ENABLED=false
    volumes:
      - /home/dazuki/qbt-hotio/config:/config
      - /home/dazuki/qbt-hotio/data:/data
      - /media/ssd/downloads:/downloads
      - /media/external:/external
